### ISSUE TITLE
Find a way to avoid resetting camera when changing surface selections

### ISSUE THREAD

**Issue by jsoules** [magland/volumeview#15]
Clicking to change the surface or vector/scalar field selection in a surface view (e.g. https://www.figurl.org/f?v=gs://figurl/volumeview-2&d=e9d66edac2246a9db4aca6c515d4b79aaa450796&channel=flatiron1&label=Test%20volumeview%20workspace or https://www.figurl.org/f?v=gs://figurl/volumeview-2&d=a997d5dd425a92ee67aa750aa48a9d9c3193f474&channel=flatiron1&label=red%20blood%20cell ) results in resetting the camera to its initial position. This is less than ideal, because it interferes with the user's ability to toggle back and forth between different field displays if the camera has been repositioned.

**Comment by magland** [comment]
I agree, this should be high priority.
