### ISSUE TITLE
camera should rotate around center of bounding box

### ISSUE THREAD

**Issue by magland** [magland/volumeview#16]
See this example: https://www.figurl.org/f?v=gs://figurl/volumeview-2&d=747778076c92df4ac817870f6f2ff6864f768962&channel=flatiron1&label=Example%20miniwasp%20surfaces

**Comment by jsoules** [comment]
Yeah, I've noticed that too.

I'm guessing the most straightforward fix would be to translate the workspace content to put the center of the bounding box at the origin--I don't really relish trying to out-smart the library orbiting camera controls. But we can reflect for a bit on whether that could have unintended negative consequences.

**Comment by magland** [comment]
seems that the bounding box may not be calculated correctly. working on it.
