### ISSUE TITLE
hide grid-specific controls when no grid in workspace

### ISSUE THREAD

**Issue by magland** [magland/volumeview#2]
When there is no grid in the workspace, we shouldn't display any controls that are grid-specific.

![image](https://user-images.githubusercontent.com/3679296/146973604-2f133174-3a26-4ff5-8bed-ce1ec520a2d6.png)

**Comment by jsoules** [comment]
https://www.figurl.org/f?v=http://localhost:3000&d=e9d66edac2246a9db4aca6c515d4b79aaa450796&channel=flatiron1&label=Test%20volumeview%20workspace is a good figure to develop against.

**Comment by magland** [comment]
> https://www.figurl.org/f?v=http://localhost:3000&d=e9d66edac2246a9db4aca6c515d4b79aaa450796&channel=flatiron1&label=Test%20volumeview%20workspace is a good figure to develop against.

But that's an example that does have a grid. So I'm not sure why that link is part of this issue...

**Comment by jsoules** [comment]
Oh, sorry, I misread--I was assuming we would suppress everything but the grid selection when no grid is selected (even if one *could* be selected).

**Comment by magland** [comment]
> Oh, sorry, I misread--I was assuming we would suppress everything but the grid selection when no grid is selected (even if one _could_ be selected).

Oh you are right, we'll want to do that too.
